export const APP_WRITE_ID = '67f40dbf002904329a3a'
export const DB_ID = 'deals'
export const COLLECTION_DEALS = 'crm-deals'
export const COLLECTION_CUSTOMERS = 'customers'
export const COLLECTION_COMMENTS = 'comments'
export const STORAGE_ID = 'storage'
